@startuml

title Parte 4

class index << (P, orchild) php>>{
Pagina inicial
...
Enlace a Listado
Enlace a Acceso
}

class acceso << (P, orchild) php>>{
Formulario Acceso
...
bbdd: include
}

class login << (P, orchild) php>>{
Proceso de verificación de login
...
bbdd: include
...
}

class logout << (P, orchild) php>>{
proceso desconectar usuario y volver a index
...
bbdd: include
}

class error << (P, orchild) php>>{
Mostrar Error
...
Enlace a Index
}

class proveedores << (P, orchild) php>>{
Listado de proveedores
...
bbdd: include
--
+ Acceso restringido a usuario logeado
+ Mostrar Usuario
+ Enlace a Logout
}


index --> acceso: link {acceso}
acceso --> login: submit
acceso --> index: link {inicio}
login --> proveedores: redirect {si login OK}
login --> error: redirect {si login Error}
proveedores --> index: link
proveedores --> logout: link {logout}
logout --> index: redirect
error --> index: link
@enduml