@startuml
hide <<formulario>> circle
class index << (P, orchild) php>>{
script: generar listado
}
class estilo << (C, orchild) css>> {
pendiente de definir
}
class funciones_bd << (F, orchild) php>>{
BD_USUARIO
BD_PASSWORD
BD_NOME
BD_CONEX_PDO
- conecta_bd()
}
class formulario_nuevo_equipo << (P, orchild) php>> {
Pedir datos para un nuevo equipo

}
class form_nuevo_equipo <<formulario>> {
- nombre: text
- desc: text
- ip: text
- ram: text

}

class SESSION << (S, orchild) _SESSION>> {
variables de sesion
}
class grabar_equipo <<php>>

index --> formulario_nuevo_equipo: link
index ..> funciones_bd: include
index ..> estilo: include
formulario_nuevo_equipo o-- form_nuevo_equipo
formulario --> grabar_equipo: submit
formulario_nuevo_equipo --|> SESSION

@enduml